const PADRAO={config:{whatsapp:'5500000000000',instagram:'dayzicakes'},produtos:[{id:'ninho',nome:'Ninho com Brigadeiro',imagem:'assets/ninho.jpg',descricao:'Massa fofinha, recheio cremoso de leite em pó e brigadeiro, cobertura de chocolate e decoração com morangos frescos.',precos:{'1kg':85,'1.5kg':120,'2kg':155,'2.5kg':190}},{id:'maracuja',nome:'Maracujá com Brigadeiro',imagem:'assets/maracuja.jpg',descricao:'Massa fofinha com recheio de maracujá e brigadeiro, trazendo o equilíbrio perfeito entre o doce e o azedinho.',precos:{'1kg':85,'1.5kg':120,'2kg':155,'2.5kg':190}},{id:'personalizado',nome:'Personalizado',imagem:'assets/personalizado.jpg',descricao:'Bolo personalizado para deixar sua comemoração ainda mais especial.',precos:{'1kg':85,'1.5kg':120,'2kg':155,'2.5kg':190}}]};
let dados=(()=>{try{return JSON.parse(localStorage.getItem('dayziCakesDados'))||structuredClone(PADRAO)}catch{return structuredClone(PADRAO)}})();
const $=id=>document.getElementById(id);const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});function salvar(){localStorage.setItem('dayziCakesDados',JSON.stringify(dados))}
function render(){
 $('listaProdutos').innerHTML=dados.produtos.map(p=>`<div class="product-item"><img src="${p.imagem}" alt=""><div><h3>${p.nome}</h3><p>A partir de ${money(p.precos['1kg'])}</p></div><div class="item-actions"><button onclick="editar('${p.id}')">✎ Editar</button><button class="delete" onclick="excluir('${p.id}')">🗑</button></div></div>`).join('')
 $('whatsapp').value=dados.config.whatsapp;$('instagram').value=dados.config.instagram;
}
window.editar=id=>{const p=dados.produtos.find(x=>x.id===id);$('editorTitulo').textContent='Editar: '+p.nome;$('id').value=p.id;$('nome').value=p.nome;$('descricao').value=p.descricao;$('p1').value=p.precos['1kg'];$('p15').value=p.precos['1.5kg'];$('p2').value=p.precos['2kg'];$('p25').value=p.precos['2.5kg'];$('foto').value='';document.querySelector('.editor').scrollIntoView({behavior:'smooth'})};
window.excluir=id=>{if(dados.produtos.length<=1)return alert('Mantenha pelo menos um produto.');if(confirm('Deseja excluir este produto?')){dados.produtos=dados.produtos.filter(p=>p.id!==id);salvar();render()}};
$('produtoForm').addEventListener('submit',async e=>{e.preventDefault();let id=$('id').value;const novo=!id;if(novo)id='produto-'+Date.now();let p=dados.produtos.find(x=>x.id===id);if(!p){p={id,nome:'',imagem:'assets/ninho.jpg',descricao:'',precos:{}};dados.produtos.push(p)}p.nome=$('nome').value.trim();p.descricao=$('descricao').value.trim();p.precos={'1kg':+$('p1').value||0,'1.5kg':+$('p15').value||0,'2kg':+$('p2').value||0,'2.5kg':+$('p25').value||0};const file=$('foto').files[0];if(file){p.imagem=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}salvar();render();$('produtoForm').reset();$('id').value='';$('editorTitulo').textContent='Editar produto';alert('Produto salvo com sucesso!')});
$('contatoForm').addEventListener('submit',e=>{e.preventDefault();dados.config.whatsapp=$('whatsapp').value.trim();dados.config.instagram=$('instagram').value.trim().replace('@','');salvar();alert('Contato salvo com sucesso!')});
$('novoProduto').onclick=()=>{$('produtoForm').reset();$('id').value='';$('editorTitulo').textContent='Novo produto';document.querySelector('.editor').scrollIntoView({behavior:'smooth'})};$('cancelar').onclick=()=>{$('produtoForm').reset();$('id').value='';$('editorTitulo').textContent='Editar produto'};render();
